from PyQt5 import QtCore, QtGui, QtWidgets


class ApplicationView(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

    def init_ui(self):
        # self == window
        self.setObjectName("self")
        self.resize(1080, 720)
        self.setMinimumSize(QtCore.QSize(1080, 720))
        self.setMaximumSize(QtCore.QSize(1080, 720))
        self.setAutoFillBackground(False)
        self.setStyleSheet("background-color:lavender")

        # central widget
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        # scroll area
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(510, 0, 551, 671))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color:rgba(255, 255, 127, 125)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 669))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        # buttons
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(20, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        self.convertButton.setFont(font)
        self.convertButton.setStyleSheet("background-color:rgb(255, 250, 80)")
        self.convertButton.setObjectName("convertButton")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(260, 630, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("background-color:rgb(255, 170, 255)")
        self.searchButton.setObjectName("searchButton")

        # radio buttons
        self.SaxApiButton = QtWidgets.QRadioButton(self.centralwidget)
        self.SaxApiButton.setGeometry(QtCore.QRect(260, 480, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.SaxApiButton.setFont(font)
        self.SaxApiButton.setStyleSheet("")
        self.SaxApiButton.setObjectName("SaxApiButton")
        self.DomApiButton = QtWidgets.QRadioButton(self.centralwidget)
        self.DomApiButton.setGeometry(QtCore.QRect(260, 530, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.DomApiButton.setFont(font)
        self.DomApiButton.setStyleSheet("")
        self.DomApiButton.setObjectName("DomApiButton")

        # check(tick) boxes
        self.surnameCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.surnameCheckButton.setGeometry(QtCore.QRect(20, 30, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.surnameCheckButton.setFont(font)
        self.surnameCheckButton.setObjectName("surnameCheckButton")
        self.facultyCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.facultyCheckButton.setGeometry(QtCore.QRect(20, 80, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.facultyCheckButton.setFont(font)
        self.facultyCheckButton.setObjectName("facultyCheckButton")
        self.departmentCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.departmentCheckButton.setGeometry(QtCore.QRect(20, 180, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.departmentCheckButton.setFont(font)
        self.departmentCheckButton.setObjectName("departmentCheckButton")
        self.majorCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.majorCheckButton.setGeometry(QtCore.QRect(20, 130, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.majorCheckButton.setFont(font)
        self.majorCheckButton.setObjectName("majorCheckButton")
        self.idCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.idCheckButton.setGeometry(QtCore.QRect(20, 330, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.idCheckButton.setFont(font)
        self.idCheckButton.setObjectName("idCheckButton")
        self.evaluationsCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.evaluationsCheckButton.setGeometry(QtCore.QRect(20, 230, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.evaluationsCheckButton.setFont(font)
        self.evaluationsCheckButton.setObjectName("evaluationsCheckButton")
        self.rankingCheckButton = QtWidgets.QCheckBox(self.centralwidget)
        self.rankingCheckButton.setGeometry(QtCore.QRect(20, 280, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.rankingCheckButton.setFont(font)
        self.rankingCheckButton.setObjectName("rankingCheckButton")

        # combo(drop menu) boxes
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 40, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(5)
        self.comboBox.setMaxCount(5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 90, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setMaxVisibleItems(5)
        self.comboBox_2.setMaxCount(5)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(190, 140, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setMaxVisibleItems(5)
        self.comboBox_3.setMaxCount(5)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(190, 190, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setMaxVisibleItems(5)
        self.comboBox_4.setMaxCount(5)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(190, 340, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setEditable(False)
        self.comboBox_5.setMaxVisibleItems(5)
        self.comboBox_5.setMaxCount(5)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(190, 290, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setMaxVisibleItems(5)
        self.comboBox_6.setMaxCount(5)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(190, 240, 281, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        self.comboBox_8.setFont(font)
        self.comboBox_8.setEditable(False)
        self.comboBox_8.setMaxVisibleItems(5)
        self.comboBox_8.setMaxCount(5)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")

        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_4.setCurrentIndex(0)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(0)
        self.comboBox_8.setCurrentIndex(0)

        # menu bar
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 21))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClear = QtWidgets.QAction(self)
        self.actionClear.setObjectName("actionClear")
        self.actionAbout = QtWidgets.QAction(self)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(self)
        self.actionSave.setObjectName("actionSave")

        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("window", "BottleNeck"))

        # buttons
        self.convertButton.setText(_translate("window", "Convert"))
        self.searchButton.setText(_translate("window", "Search"))

        # radio buttons
        self.SaxApiButton.setText(_translate("window", "SAX API"))
        self.DomApiButton.setText(_translate("window", "DOM API"))

        # check(tick) boxes
        self.surnameCheckButton.setText(_translate("window", "Surname"))
        self.facultyCheckButton.setText(_translate("window", "Faculty"))
        self.departmentCheckButton.setText(_translate("window", "Department"))
        self.majorCheckButton.setText(_translate("window", "Major"))
        self.idCheckButton.setText(_translate("window", "ID"))
        self.evaluationsCheckButton.setText(_translate("window", "Evaluations"))
        self.rankingCheckButton.setText(_translate("window", "Ranking"))

        # combo(drop menu) boxes
        # surnames
        self.comboBox.setItemText(0, _translate("window", "Pevny"))
        self.comboBox.setItemText(1, _translate("window", "Olefir"))
        self.comboBox.setItemText(2, _translate("window", "Fesiuk"))
        self.comboBox.setItemText(3, _translate("window", "Vishnyak"))
        self.comboBox.setItemText(4, _translate("window", "Algin"))

        # faculty
        self.comboBox_2.setItemText(0, _translate("window", "CSC"))
        self.comboBox_2.setItemText(1, _translate("window", "IT"))
        self.comboBox_2.setItemText(2, _translate("window", "MAM"))
        self.comboBox_2.setItemText(3, _translate("window", "Chemistry"))
        self.comboBox_2.setItemText(4, _translate("window", "History"))

        # major
        self.comboBox_3.setItemText(0, _translate("window", "122"))
        self.comboBox_3.setItemText(1, _translate("window", "121"))
        self.comboBox_3.setItemText(2, _translate("window", "112"))
        self.comboBox_3.setItemText(3, _translate("window", "027"))
        self.comboBox_3.setItemText(4, _translate("window", "102"))

        # department
        self.comboBox_4.setItemText(0, _translate("window", "OR"))
        self.comboBox_4.setItemText(1, _translate("window", "OOP"))
        self.comboBox_4.setItemText(2, _translate("window", "Mathan"))
        self.comboBox_4.setItemText(3, _translate("window", "UH"))
        self.comboBox_4.setItemText(4, _translate("window", "H2O"))

        # id
        self.comboBox_5.setItemText(0, _translate("window", "100"))
        self.comboBox_5.setItemText(1, _translate("window", "200"))
        self.comboBox_5.setItemText(2, _translate("window", "300"))
        self.comboBox_5.setItemText(3, _translate("window", "400"))
        self.comboBox_5.setItemText(4, _translate("window", "500"))

        # ranking
        self.comboBox_6.setItemText(0, _translate("window", "1"))
        self.comboBox_6.setItemText(1, _translate("window", "2"))
        self.comboBox_6.setItemText(2, _translate("window", "3"))
        self.comboBox_6.setItemText(3, _translate("window", "4"))
        self.comboBox_6.setItemText(4, _translate("window", "5"))

        # evaluations
        self.comboBox_8.setItemText(0, _translate("window", "10"))
        self.comboBox_8.setItemText(1, _translate("window", "9"))
        self.comboBox_8.setItemText(2, _translate("window", "8"))
        self.comboBox_8.setItemText(3, _translate("window", "7"))
        self.comboBox_8.setItemText(4, _translate("window", "6"))

        # menu bar
        self.menuFile.setTitle(_translate("window", "File"))
        self.actionOpen.setText(_translate("window", "Open"))
        self.actionClear.setText(_translate("window", "Clear"))
        self.actionAbout.setText(_translate("window", "About"))
        self.actionSave.setText(_translate("window", "Save"))
        self.actionSave.setShortcut(_translate("window", "Ctrl+S"))
